------------ 회원 ------------------------------
CREATE TABLE "MEMBER"(
	MEMBER_ID VARCHAR2(20)PRIMARY KEY, -- 아이디
	MEMBER_PW VARCHAR2(20) NOT NULL, -- 비번
	MEMBER_NICKNAME VARCHAR2(20) NOT NULL, -- 이름
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,  -- 생성일
	MEMBER_DEL_FL	CHAR(1)	DEFAULT 'N'	NOT NULL -- 탈퇴여부
);
	
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NICKNAME IS '회원 이름';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '생성일';
COMMENT ON COLUMN "MEMBER".MEMBER_DEL_FL IS '탈퇴여부';


INSERT INTO "MEMBER" VALUES
('user01', 'pass01', '유저일', DEFAULT, 'N');
INSERT INTO "MEMBER" VALUES
('user02', 'pass02', '유저이', DEFAULT, 'N');


	
---------  게시판  -------------------------------------------------	
CREATE TABLE BOARD(
	BOARD_NO NUMBER PRIMARY KEY, -- 게시글 번호
	BOARD_TITLE VARCHAR2(50), -- 게시글 제목
	BOARD_CONTENT VARCHAR2(500), -- 게시글 내용
	MEMBER_ID VARCHAR2(20) CONSTRAINT MEMBER_ID_FK REFERENCES "MEMBER",
	BOARD_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL -- 삭제 여부
	
);


COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN BOARD.BOARD_DEL_FL IS '삭제 여부';


INSERT INTO BOARD VALUES(1, '게시글1', '1번 게시글 내용', 'user01', DEFAULT);
INSERT INTO BOARD VALUES(2, '게시글2', '2번 게시글 내용', 'user02', DEFAULT);
INSERT INTO BOARD VALUES(3, '게시글3', '3번내용', 'user01', DEFAULT);



COMMIT;
----------------- 시퀀스 --------------------
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_HIT FROM BOARD;






	
COMMIT;

SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_HIT, MEMBER_ID FROM BOARD;
		WHERE MEMBER_ID = 'user01';

